services:
    openpp_oauth_server.admin.client:
        class: Openpp\OAuthServerBundle\Admin\ClientAdmin
        arguments: [~, Openpp\OAuthServerBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    openpp_oauth_server.oauth_event_listener:
        class: Openpp\OAuthServerBundle\EventListener\OAuthEventListener
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

    openpp_oauth_server.api.controller.user:
        class: Openpp\OAuthServerBundle\Controller\Api\UserController

    openpp_oauth_server.api.controller.verify:
        class: Openpp\OAuthServerBundle\Controller\Api\VerifyController
